apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i6knkdtm1-go 
  janus-idp.io/tekton: i6knkdtm1-go
  backstage.io/kubernetes-id: i6knkdtm1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i6knkdtm1-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  